on:
    push:
        branches:
            - main
jobs:
    print_working:
        runs-on: ubuntu-latest
        steps:
            - name: Say Working
              run: echo {{input.username}} ran the job on ${whoami}
